### ISSUE TITLE
Unnecessary lines as comments

### ISSUE THREAD

**Issue by DipanshKhandelwal** [fossasia/mvisc#2]
There are lots of unnecessary lines of codes kept as comments while in development process.

**Comment by GOVINDDIXIT** [comment]
I would like to work on this issue

**Comment by SayanDas92** [comment]
I have addressed this issue and generated a pull request. I'm a beginner. So, please guide me.

**Comment by wijjj** [comment]
Hey @SayanDas92 I am one of the authors of Zooracle. Together with a friend we came up with the idea in 2015. In 2019 we were asking Mario to take down this repository, as there was no real engagement as initially expected. As you can see he refused. I can spare you some headaches and tell you that this repo is missing essential steps to perform the desired computer vision identification (which I luckily forgot to push 3 years ago). I wish I could support you with the project, but unfortunately at the moment I am just too busy. But I think if you are really interested in the topic you will find a way to do it. There's a lot of helpful literature out there nowadays. And probably also more modern approaches.

**Comment by mariobehling** [comment]
Thanks @wijjj, that is correct, the repo is outdated, but it is still a brilliant idea and maybe it will be possible to take up the thread later. It was great that you released it under the GPL and I hope the idea continues to serve as an inspiration for others who would like to build this as a free and open source solution. 

@SayanDas92 @DipanshKhandelwal If you are interested in topics around data visualization, AI and Python definitely also check out https://github.com/fossasia/visdom

Closing this due the above.
